#! /bin/bash

export DB_HOST="localhost"
export DB_USER="admin"
export DB_PASS="admin"
export DB_NAME="portfolio_insights"
export DB_PORT=5432
export REDISCLOUD_URL="redis://127.0.0.1:6379"
export PORT=3000
export HOST_NAME="ajab-gajab.com"
export APP_DIR="/home/ubuntu/app/portfolio-insights"
export PYTHON_EXEC="python3"
